
tasks:
  - name: initialize
    before: |
      curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
      source /workspace/.cargo/env

    init: |
      echo "🚀"
      
vscode:
  extensions:
    - rust-lang.rust