#image:
#  file: .gitpod.dockerfile

image: k33g/wasm-university-rust:0.0.0

  
tasks:
  - name: initialize
    before: |
      echo "🎉"

    init: |
      echo "🚀"
      npm install
      
ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
    